import React, { useEffect, useRef } from 'react';
import type { CodeGuideData } from '@ainotate/shared/guide';
import { renderInlineMarkdown } from '../../utils/renderInlineMarkdown';
import { useReviewState } from '../../dock/ReviewStateContext';
import { GuideSectionCard } from './GuideSectionCard';
import { GuideDiffSection } from './GuideDiffSection';

interface GuideViewProps {
  guide: CodeGuideData;
  reviewed: boolean[];
  onToggleReviewed: (index: number) => void;
  /** e.g. "Claude" / "Codex" — omitted when the generating job/engine is unknown
   *  (demo guide, or a job the client no longer has in its jobs list). */
  engineLabel?: string;
  focusedFile: string | null;
  onFocusFile: (filePath: string) => void;
}

/**
 * The generated guide itself: title + intent, ordered section chapters (each a
 * two-column overview/diffs card), and a trailing "Everything else" bucket for
 * files the model didn't place anywhere (the server's coverage guarantee —
 * every changed file appears exactly once across sections + unplacedFiles).
 */
export const GuideView: React.FC<GuideViewProps> = ({ guide, reviewed, onToggleReviewed, engineLabel, focusedFile, onFocusFile }) => {
  const total = guide.sections.length;
  const reviewedCount = reviewed.filter(Boolean).length;
  const state = useReviewState();
  const unplacedElements = useRef(new Map<string, HTMLDivElement | null>());

  // Reveal channel for the "Everything else" bucket — the section-card effect
  // only covers PLACED files, so a sidebar jump (annotation click / AI line
  // citation) targeting an unplaced file would focus nothing and appear dead.
  // No collapse handling needed here: the bucket is always rendered.
  const revealTarget =
    state.guideRevealFile && guide.unplacedFiles?.includes(state.guideRevealFile.path)
      ? state.guideRevealFile
      : null;
  useEffect(() => {
    if (!revealTarget) return;
    onFocusFile(revealTarget.path);
    const raf = requestAnimationFrame(() => {
      unplacedElements.current.get(revealTarget.path)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
    return () => cancelAnimationFrame(raf);
    // Token identifies the reveal event (increments on every set) — path and
    // handler churn must not re-fire it. Mirrors GuideSectionCard's effect.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [revealTarget?.token]);

  return (
    // Full width — the guide owns the whole center area, like the wireframe.
    <div className="w-full px-10 py-8">
      <div className="max-w-[72ch]">
        <h1 className="text-[22px] font-semibold tracking-tight text-foreground [text-wrap:balance]">{guide.title}</h1>
        {guide.intent && (
          <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">{renderInlineMarkdown(guide.intent)}</p>
        )}
        <p className="mt-2 font-mono text-[11px] text-muted-foreground/60">
          {total} section{total !== 1 ? 's' : ''}
          {reviewedCount > 0 && ` · ${reviewedCount}/${total} reviewed`}
          {engineLabel && ` · generated by ${engineLabel}`}
        </p>
      </div>

      <div className="mt-6 space-y-4">
        {guide.sections.map((section, i) => (
          <GuideSectionCard
            key={`${section.title}:${i}`}
            section={section}
            index={i}
            total={total}
            reviewed={!!reviewed[i]}
            onToggleReviewed={() => onToggleReviewed(i)}
            focusedFile={focusedFile}
            onFocusFile={onFocusFile}
          />
        ))}

        {guide.unplacedFiles && guide.unplacedFiles.length > 0 && (
          <div className="overflow-hidden rounded-lg border border-border/50 bg-card">
            <div className="border-b border-border/40 px-5 py-3.5">
              <h3 className="text-[15px] font-semibold text-foreground">Everything else</h3>
              <p className="mt-0.5 text-[12px] text-muted-foreground/70">
                Changed files the guide didn't place into a section — shown so nothing is silently left out.
              </p>
            </div>
            <div className="space-y-4 bg-muted/[0.07] px-4 py-4">
              {guide.unplacedFiles.map((file) => (
                <div key={file} ref={(el) => { unplacedElements.current.set(file, el); }}>
                  <GuideDiffSection
                    diffRef={{ file }}
                    isFocused={focusedFile === file}
                    onFocus={() => onFocusFile(file)}
                  />
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
